# Provision an EC2 instance
template_path: templates/managed-ec2-v4.yaml
stack_name: iwanna-instance
parameters:
  # The Sage deparment (Platform, CompOnc, SysBio, Governance, etc..)
  Department: "Platform"
  # The Sage project (Infrastructure, amp-ad, ntap, dream, etc..)
  Project: "Infrastructure"
  # The resource owner
  OwnerEmail: "joe.smith@sagebase.org"
  # (Optional) EC2 instance type, default is "t2.nano" (other available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t2.medium"
  # (Optional) ID of the base AMI (supported distros: AWS linux)
  AMIId: "ami-0d051218cbaf3405a"      # AMI with my R packages
  # (Optional) EC2 boot volume size in GB, default is 8GB, Max is 1000GB
  VolumeSize: "50"

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !notify_ec2

